Adding miryoku layout for redox_w
manna-harbour/qmk_firmware pull request #6
Opened 2020-10-12 14:02 UTC by bromanko

## Description

Adding a miryoku keymap for the Redox Wireless.
I had some trouble generating the file using Doom Emacs. If you could confirm the files generate properly for you and still compile via `make` that would be appreciated.

## Types of Changes

- [ ] Core
- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement/optimization
- [ ] Keyboard (addition or update)
- [x] Keymap/layout/userspace (addition or update)
- [ ] Documentation

## Issues Fixed or Closed by This PR

* 

## Checklist

- [x] My code follows the code style of this project: [**C**](https://docs.qmk.fm/#/coding_conventions_c), [**Python**](https://docs.qmk.fm/#/coding_conventions_python)
- [x] I have read the [**PR Checklist** document](https://docs.qmk.fm/#/pr_checklist) and have made the appropriate changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING** document](https://docs.qmk.fm/#/contributing).
- [ ] I have added tests to cover my changes.
- [x] I have tested the changes and verified that they work and don't break anything (as well as I can manage).

2020-10-13 23:01 UTC, manna-harbour commented
Thanks for the PR!

What kind of trouble did you have?  You need to manually create the new directory first, but then it should just be org-babel-tangle (C-c C-v t) to generate everything.

2020-10-13 23:08 UTC, manna-harbour requested changes
I like to have the alpha columns lining up to make the relationship a little easier to see.

2020-10-13 23:08 UTC, manna-harbour commented on keyboards/redox_w/keymaps/manna-harbour_miryoku/config.h
> +     N30, N31, K32, K33, K34,               K35, K36, K37, N38, N39\
```suggestion
     K00, K01, K02, K03, K04,                         K05, K06, K07, K08, K09,\
     K10, K11, K12, K13, K14,                         K15, K16, K17, K18, K19,\
     K20, K21, K22, K23, K24,                         K25, K26, K27, K28, K29,\
     N30, N31, K32, K33, K34,                         K35, K36, K37, N38, N39\
```

2020-10-13 23:08 UTC, manna-harbour commented on users/manna-harbour_miryoku/miryoku.org
> +     N30, N31, K32, K33, K34,               K35, K36, K37, N38, N39\
```suggestion
     K00, K01, K02, K03, K04,                         K05, K06, K07, K08, K09,\
     K10, K11, K12, K13, K14,                         K15, K16, K17, K18, K19,\
     K20, K21, K22, K23, K24,                         K25, K26, K27, K28, K29,\
     N30, N31, K32, K33, K34,                         K35, K36, K37, N38, N39\
```

2020-10-13 23:17 UTC, manna-harbour requested changes
I like to have the alpha columns lining up to make the relationship a little easier to see, and exactly one extra column's space between the 2 halves.

2020-10-13 23:17 UTC, manna-harbour commented on users/manna-harbour_miryoku/miryoku.org
> +)
```suggestion
#define LAYOUT_miryoku(\
     K00, K01, K02, K03, K04,                          K05, K06, K07, K08, K09,\
     K10, K11, K12, K13, K14,                          K15, K16, K17, K18, K19,\
     K20, K21, K22, K23, K24,                          K25, K26, K27, K28, K29,\
     N30, N31, K32, K33, K34,                          K35, K36, K37, N38, N39\
)\
LAYOUT(\
XXX, XXX, XXX, XXX, XXX, XXX,                          XXX, XXX, XXX, XXX, XXX, XXX,\
XXX, K00, K01, K02, K03, K04, XXX,                XXX, K05, K06, K07, K08, K09, XXX,\
XXX, K10, K11, K12, K13, K14, XXX,                XXX, K15, K16, K17, K18, K19, XXX,\
XXX, K20, K21, K22, K23, K24, XXX, XXX,      XXX, XXX, K25, K26, K27, K28, K29, XXX,\
XXX, XXX, XXX, XXX,    K32,   K33, K34,      K35, K36,    K37,   XXX, XXX, XXX, XXX\
)
```

2020-10-13 23:17 UTC, manna-harbour commented on keyboards/redox_w/keymaps/manna-harbour_miryoku/config.h
> +)
```suggestion
#define LAYOUT_miryoku(\
     K00, K01, K02, K03, K04,                          K05, K06, K07, K08, K09,\
     K10, K11, K12, K13, K14,                          K15, K16, K17, K18, K19,\
     K20, K21, K22, K23, K24,                          K25, K26, K27, K28, K29,\
     N30, N31, K32, K33, K34,                          K35, K36, K37, N38, N39\
)\
LAYOUT(\
XXX, XXX, XXX, XXX, XXX, XXX,                          XXX, XXX, XXX, XXX, XXX, XXX,\
XXX, K00, K01, K02, K03, K04, XXX,                XXX, K05, K06, K07, K08, K09, XXX,\
XXX, K10, K11, K12, K13, K14, XXX,                XXX, K15, K16, K17, K18, K19, XXX,\
XXX, K20, K21, K22, K23, K24, XXX, XXX,      XXX, XXX, K25, K26, K27, K28, K29, XXX,\
XXX, XXX, XXX, XXX,    K32,   K33, K34,      K35, K36,    K37,   XXX, XXX, XXX, XXX\
)
```

2020-10-14 13:04 UTC, bromanko commented
> What kind of trouble did you have? 

When I run tangle it overwrites the keymap in your user folder with all empty arrays.

2020-10-14 23:53 UTC, manna-harbour commented
This is ready to merge at 0fe7d19, but it looks like you accidentally incorporated some local changes after that.

2020-10-14 23:56 UTC, manna-harbour commented
> When I run tangle it overwrites the keymap in your user folder with all empty arrays.

Are there any errors in `*Messages*`?  What versions of emacs, org, and python are you on?

2020-10-15 00:03 UTC, manna-harbour requested changes
This is ready to merge at 0fe7d19, but it looks like you accidentally incorporated some local changes after that.

2020-10-15 02:29 UTC, closed without merging

2020-10-15 02:30 UTC, manna-harbour commented
You can just reset and force push to revert the later changes.